### PR TITLE
Update ReadMe

### LINKED ISSUE #12: PostmarkApp does support open, click, and link tracking, so does Amazon SES now
> This is particularly useful if you rely on an Email Service Provider (ESP) such as Amazon SES or PostmarkApp that does not provide open and click tracking.

Source: https://postmarkapp.com/

image

ReadMe should be updated accordingly.

Edit: Amazon SES now supports this as well:  
https://aws.amazon.com/about-aws/whats-new/2017/08/amazon-ses-introduces-open-and-click-metrics-for-tracking-customer-engagement/

### PR DESCRIPTION
**Pull request by GabLeRoux**
closes #12

### CODE REVIEW

**Comment by mikicz** [comment]
It's been three years since the last commit in this repo, it's unlikely it's gonna get merged

**Comment by GabLeRoux** [comment]
yeah I know, but what if it does get merged? What will it mean? ;) This library still works even tho it did not change in a long time. 🙃

**Comment by demerzel21** [comment]
If this library stopped working, what would be your preferred alternative?

**Comment by mikicz** [comment]
Recently I actually forked this repository and released a fixed up version on PYPI because the package broke with an updated django-axes. I am planning to support the current functionality of the package for the near feature, basically keep the tests passing with the supported Python and Django versions.

https://github.com/mikicz/pytracking
https://pypi.org/project/pytracking2/

**Comment by GabLeRoux** [comment]
@mikicz will you be publishing to pypy too? just wondering. 
@bartdag I know it's been a while, but maybe adding @mikicz as a contributor could make some sense.

**Comment by mikicz** [comment]
Yeah I have already published the package to PYPI (pytracking2 instead of pytracking, https://pypi.org/project/pytracking2/).
If I was given permissions for this repo and permissions on PYPI to release packages, I would happily push it to the original packages instead.

**Comment by bartdag** [comment]
Hi guys, let me get back to you by next week about this pull request and making mikicz a contributor.

We're still using pytracking in production to track tens of thousands of emails per day, but I understand that the landscape changed (Postmark and SES can now track opens and clicks). 

We created this library because we were tired to always reimplement a webhook when we moved from mandrill, then sparkpost and finally Amazon SES. 

It's also a piece of code that never gave us real trouble and runs smoothly so we did not see the need to urgently fix anything :-)

Cheers and thanks for this discussion. Our dev team was happily surprised to see that it was useful to others!

**Comment by mikicz** [comment]
Hi, yes that all makes complete sense - why fix something that isn't broken. We've implemented the package into our tracking on a bit custom solution at the company I work for and it's all been very smooth since, only recently when we were updating packages pytracking broke, because of the newest version django-ipware. If that package wasn't used by our other dependencies I would gladly use the old version of django-ipware to continue using pytracking as is, but we made decision to update our dependencies quite often, so I used a different fork and made some small updates myself and released to PyPI so the installation is bit easier and so other people can use it as well...

As I said, I am gonna maintain my fork either way so it doesn't break our stuff, but I'd be as happy to do the maintenance here...

**Comment by bartdag** [comment]
Merged. Thanks!

**Pull request merged**
