### PR TITLE
Update django-ipware, Test with Github Actions

### LINKED ISSUE #11: Package breaks with django-ipware>=3
Pretty much title, the version 3 changed some APIs causing this package to break

### PR DESCRIPTION
**Pull request by mjnaderi**
Hi,

This PR fixes #11. Plus I re-structured tests and added Github Actions for running tests against Python 3.6-3.9 and Django 1.11-3.1.

### CODE REVIEW

**Comment by cnelson** [comment]
@bartdag any chance of getting this merged?  ipware has is up to 4.x now, pinning this lib to such an old version makes it hard to use :(

**Comment by jonathanmach** [comment]
Is this project still being mantained?

**Comment by mikicz** [comment]
It doesn't seem like this repo is being maintained so a while back I forked it and now I maintain a fork at https://github.com/mikicz/pytracking released to https://pypi.org/project/pytracking2/

**Comment by jonathanmach** [comment]
> It doesn't seem like this repo is being maintained so a while back I forked it and now I maintain a fork at https://github.com/mikicz/pytracking released to https://pypi.org/project/pytracking2/

That's helpful, thanks @mikicz !

**Comment by bartdag** [comment]
working on it right now ;-p

**Comment by bartdag** [comment]
Thank you @mjnaderi . Almost a year later, we merged your wonderful contribution! We'll try to publish on pypi soon.

**Comment by bartdag** [comment]
Deployed on pypi: https://pypi.org/project/pytracking/

**Comment by jonathanmach** [comment]
Great stuff @bartdag! Very much appreciated!

**Comment by mjnaderi** [comment]
@bartdag Thanks for merging. :tada:  Now we can use the original package instead of our fork.

**Pull request closed without merging**
